/*
 * generated by Xtext 2.41.0.M2
 */
package com.drodo.gbsokoban.ide;

import com.drodo.gbsokoban.GBSokobanRuntimeModule;
import com.drodo.gbsokoban.GBSokobanStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GBSokobanIdeSetup extends GBSokobanStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GBSokobanRuntimeModule(), new GBSokobanIdeModule()));
	}
	
}
