/*
 * generated by Xtext 2.41.0.M2
 */
package com.drodo.gbsokoban;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GBSokobanStandaloneSetup extends GBSokobanStandaloneSetupGenerated {

	public static void doSetup() {
		new GBSokobanStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
