/*
 * generated by Xtext 2.41.0.M2
 */
package com.drodo.gbsokoban;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GBSokobanRuntimeModule extends AbstractGBSokobanRuntimeModule {
}
